# Demo of some `numpy` features

## MCS 275 Spring 2024 - David Dumas

This is a quick tour of some `numpy` features.  For more detail see:
* [Chapter 2 of VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
* [The numpy documentation](https://numpy.org/doc/stable/)

## Importing the module

And checking the version.

In [1]:
import numpy as np
print(np.__version__)

1.21.5


## Creating arrays

They are iterable and type-homogeneous.  Can make one from any suitable iterable.

[List of built-in dtypes](https://numpy.org/doc/stable/reference/arrays.scalars.html#arrays-scalars-built-in).

In [4]:
x = np.array( [-3,5,91,45,16,5.1] )

In [5]:
x

array([-3. ,  5. , 91. , 45. , 16. ,  5.1])

In [6]:
A = np.array([
    [1,7],
    [0,0],
    [5,-2],
    [-3,-8]
]
)

In [7]:
A

array([[ 1,  7],
       [ 0,  0],
       [ 5, -2],
       [-3, -8]])

In [8]:
long_vector = np.array( range(10_000) )

In [9]:
long_vector

array([   0,    1,    2, ..., 9997, 9998, 9999])

Check number of dimensions

In [10]:
x.ndim

1

In [11]:
A.ndim

2

Check shape (size in each dimension)

In [13]:
x.shape

tuple

In [14]:
# how many elements are in the vector x?
x.shape[0]

6

In [15]:
A.shape

(4, 2)

In [16]:
A

array([[ 1,  7],
       [ 0,  0],
       [ 5, -2],
       [-3, -8]])

Check "length" (first elt of shape)

In [17]:
len(x)  # same as x.shape[0]

6

In [18]:
len(A)

4

Check data type

In [20]:
x

array([-3. ,  5. , 91. , 45. , 16. ,  5.1])

In [19]:
x.dtype

dtype('float64')

Data type typically inferred but can be specified (potential lossy process)

In [21]:
y = np.array([5,6,0,0,2,5,1], dtype="float64")

In [22]:
y

array([5., 6., 0., 0., 2., 5., 1.])

`uint8` means *u*nsigned *int*eger of 8 bits.  
Minimum is 0, maximum is 255.


In [26]:
z = np.array([2,-7,0,100,200,300,500,10000], dtype="uint8")
print(z)

[  2 249   0 100 200  44 244  16]


Can make a 2D array (matrix) from a list of lists

## Filled arrays

Can fill with zeros, ones, or make an array full of a general value.

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros( (5,15) )

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((3,3), dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.zeros((3,3), dtype="bool")

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [32]:
True == 1

True

Can also ask for an array filled with random values (floats between 0 and 1, never exactly 1, uniformly distributed).  Note `np.random` is a submodule, you want `np.random.random(...)`

In [33]:
np.random.random(10)

array([0.28614261, 0.65501536, 0.90492018, 0.75424583, 0.13442153,
       0.73298525, 0.09509374, 0.97043484, 0.40662834, 0.56457747])

In [35]:
np.random.random((10,3))

array([[0.54226901, 0.62847445, 0.44242965],
       [0.01640402, 0.5690059 , 0.84967372],
       [0.11036265, 0.80254551, 0.40854342],
       [0.74652201, 0.96222029, 0.8792049 ],
       [0.12861055, 0.5678108 , 0.18391426],
       [0.88869421, 0.96376697, 0.29301565],
       [0.80092353, 0.61597063, 0.0138651 ],
       [0.52926654, 0.99438864, 0.83511244],
       [0.35222131, 0.1606797 , 0.67823432],
       [0.26783098, 0.08364909, 0.2833546 ]])

## Special things about 2D arrays

Identity (eye-dentity) matrix

Transpose

## Vector algebra

In [36]:
u = np.array( [2,5,8] )
v = np.array( [3,0,0])
w = np.array( [1,-2,1] )

Dot product (and vector length)

In [37]:
np.dot(v,w)

3

In [38]:
v.dot(w)

3

In [39]:
w.dot(v)

3

In [40]:
u.dot(u) ** 0.5  # length of the vector u (Euclidean sense)

9.643650760992955

Scalar multiplication

In [41]:
1.5 * u

array([ 3. ,  7.5, 12. ])

In [42]:
u

array([2, 5, 8])

Elementwise sum

In [43]:
u

array([2, 5, 8])

In [44]:
v

array([3, 0, 0])

In [45]:
u + v

array([5, 5, 8])

Elementwise product (?!)

In [46]:
u * v  # usually not what you want in geometric setting

array([6, 0, 0])

## Arithmetic progressions

* `np.arange` is `start`, `stop`, `step`
* `np.linspace` is `first`,`last`,`number`

In [47]:
list(range(2,20,5))

[2, 7, 12, 17]

In [48]:
np.arange(2,20,5)

array([ 2,  7, 12, 17])

In [49]:
np.arange(2,20,0.6)

array([ 2. ,  2.6,  3.2,  3.8,  4.4,  5. ,  5.6,  6.2,  6.8,  7.4,  8. ,
        8.6,  9.2,  9.8, 10.4, 11. , 11.6, 12.2, 12.8, 13.4, 14. , 14.6,
       15.2, 15.8, 16.4, 17. , 17.6, 18.2, 18.8, 19.4])

In [50]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [51]:
np.linspace(100,120,300)

array([100.        , 100.06688963, 100.13377926, 100.2006689 ,
       100.26755853, 100.33444816, 100.40133779, 100.46822742,
       100.53511706, 100.60200669, 100.66889632, 100.73578595,
       100.80267559, 100.86956522, 100.93645485, 101.00334448,
       101.07023411, 101.13712375, 101.20401338, 101.27090301,
       101.33779264, 101.40468227, 101.47157191, 101.53846154,
       101.60535117, 101.6722408 , 101.73913043, 101.80602007,
       101.8729097 , 101.93979933, 102.00668896, 102.0735786 ,
       102.14046823, 102.20735786, 102.27424749, 102.34113712,
       102.40802676, 102.47491639, 102.54180602, 102.60869565,
       102.67558528, 102.74247492, 102.80936455, 102.87625418,
       102.94314381, 103.01003344, 103.07692308, 103.14381271,
       103.21070234, 103.27759197, 103.34448161, 103.41137124,
       103.47826087, 103.5451505 , 103.61204013, 103.67892977,
       103.7458194 , 103.81270903, 103.87959866, 103.94648829,
       104.01337793, 104.08026756, 104.14715719, 104.21

## Accessing items

In [52]:
x

array([-3. ,  5. , 91. , 45. , 16. ,  5.1])

In [55]:
x[2] # 0-based index 2

91.0

In [54]:
for component in x:
    print(component,"is one of the components of that vector")
    print("its type is",type(component))

-3.0 is one of the components of that vector
its type is <class 'numpy.float64'>
5.0 is one of the components of that vector
its type is <class 'numpy.float64'>
91.0 is one of the components of that vector
its type is <class 'numpy.float64'>
45.0 is one of the components of that vector
its type is <class 'numpy.float64'>
16.0 is one of the components of that vector
its type is <class 'numpy.float64'>
5.1 is one of the components of that vector
its type is <class 'numpy.float64'>


Multidimensional indexing: use a tuple of indices

In [56]:
A

array([[ 1,  7],
       [ 0,  0],
       [ 5, -2],
       [-3, -8]])

In [57]:
A[2,1]

-2

In [58]:
x = 5,6,7,8,8,1

In [59]:
type(x)

tuple

Omitted indices at the end mean "everything from those dimensions"

Using `:` as an index means "everything from that dimension"

## Assigning items

**`numpy` arrays are mutable** 😱

## Slices

Can combine slice notation with multiple indices.

Slices return **views**, not copies.

## Equality and bool

`.all()` checks if an array of booleans is all `True`.

## Ufuncs

Functions that automatically apply to each entry in an array.

### Some arrays to operate on

### Examples of numpy ufuncs

Let $f(x) = 3x^2 - 8x + 14$.  Apply $f$ to each element of array `v`.

## Broadcasting

## Aggregations

`sum`, `max`, `min`, `argmax`, `argmin`, `mean`, `all`, `any`, `array_equal`

## Masks

## Pillow integration

* `np.array(img)` just works, if `img` is a `PIL.Image` object
* Use `PIL.Image.fromarray(A)` to make an image from an array
    * Shape `(height,width)` and dtype `uint8` for grayscale
    * Shape `(height,width,3)` and dtype `uint8` for color (last axis is red, green, blue)