# Demo of some `numpy` features

## MCS 275 Spring 2024 - David Dumas

This is a quick tour of some `numpy` features.  For more detail see:
* [Chapter 2 of VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
* [The numpy documentation](https://numpy.org/doc/stable/)

## Importing the module

And checking the version.

In [156]:
import numpy as np
np.__version__

'1.21.5'

## Creating arrays

They are iterable and type-homogeneous.  Can make one from any suitable iterable.

[List of built-in dtypes](https://numpy.org/doc/stable/reference/arrays.scalars.html#arrays-scalars-built-in).

In [3]:
# `np.array` will convert from an iterable
x = np.array([2,4,8,16,32])

In [8]:
# List of lists -> 4 row, 3 column matrix (2 dimensional array)
A = np.array([[1,2,3],[4,5,6],[7,8,9],[0,2,0]])

In [11]:
# nice display
print(x)
print()
print(A)

[ 2  4  8 16 32]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 0]]


In [13]:
# ndarray class
type(x)

numpy.ndarray

Check number of dimensions

In [6]:
x.ndim # how many dimensions?

1

In [14]:
A.ndim

2

Check shape (size in each dimension)

In [7]:
x.shape # size in each dimension, as a tuple

(5,)

In [15]:
A.shape

(4, 3)

Check "length" (first elt of shape)

In [16]:
len(x) # number of items in the vector

5

In [17]:
len(A) # number of rows in the matrix = A.shape[0]

4

In general, `len(m)` means `m.shape[0]` if `m` is a numpy array.

Check data type

In [18]:
x.dtype # int64 means (signed) integer, 64 bits

dtype('int64')

Data type typically inferred but can be specified (potential lossy process)

In [19]:
# Given a mix of integers and floats, numpy
# will choose a floating point dtype
y= np.array([5,6,7,7.289])

In [20]:
y

array([5.   , 6.   , 7.   , 7.289])

In [21]:
y.dtype # float64 means float, 64 bits (double)

dtype('float64')

In [22]:
y_force_int = y= np.array([5,6,7,7.289], dtype="int")

In [25]:
# Notice we lost precision by specifying dtype int
y_force_int

array([5, 6, 7, 7])

In [24]:
# Notice numpy chose a precise type compatible with
# the request "int"
y_force_int.dtype

dtype('int64')

In [26]:
# uint8 means UNSIGNED integer, 8 bits
# UNSIGNED = only 0 and positive values
# range is 0...255
z = np.array([1,-1,2,100,300,500,800,16384], dtype="uint8")

In [27]:
z

array([  1, 255,   2, 100,  44, 244,  32,   0], dtype=uint8)

In [28]:
# Why did 300 appear as 44 in the array above?
300 % 256

44

## Filled arrays

Can fill with zeros, ones, or make an array full of a general value.

In [29]:
# Filled with zeros
np.zeros( (3,12), dtype="int64")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
# Filled with ones
np.ones( (6,2), dtype="float64")

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
# Filled with one value
np.full( (7,4), 42, dtype="uint8" )

array([[42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42]], dtype=uint8)

Can also ask for an array filled with random values (floats between 0 and 1, never exactly 1, uniformly distributed).  Note `np.random` is a submodule, you want `np.random.random(...)`

In [32]:
# Filled with random numbers between 0 and 1
np.random.random( (4,5) )  # argument is the shape

array([[0.84985369, 0.52904623, 0.06757972, 0.60749338, 0.44579558],
       [0.94276045, 0.22398809, 0.99290933, 0.9505469 , 0.65531365],
       [0.0944089 , 0.67245052, 0.25851387, 0.81402906, 0.02156303],
       [0.16531779, 0.87858936, 0.60636781, 0.24837322, 0.67221406]])

## Special things about 2D arrays

Identity (eye-dentity) matrix

$$
I_{3 \times 3} = \begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$$

In [157]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
np.eye(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [159]:
np.eye(4,dtype="int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [160]:
np.eye(4,dtype="bool")

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

Transpose

In [164]:
A = np.array([[1,2],[5,8],[0,0],[2,3]])
A

array([[1, 2],
       [5, 8],
       [0, 0],
       [2, 3]])

In [165]:
A.T

array([[1, 5, 0, 2],
       [2, 8, 0, 3]])

In [ ]:
A[i,j] == A.T[j,i] # for any i,j where this makes sense

In [166]:
A.shape

(4, 2)

In [168]:
A.T.shape

(2, 4)

## Vector algebra

In [33]:
# two 3-dimensional vectors
v = np.array([1,2,5])
w = np.array([4,-8,0])

Dot product (and vector length)

In [34]:
v.dot(w) # dot product
#   1*4 + 2*(-8) + 5*0

-12

In [35]:
v.dot(v)**0.5 # length

5.477225575051661

Scalar multiplication

In [36]:
1.8 * v # scalar multiplication

array([1.8, 3.6, 9. ])

Elementwise sum

In [37]:
v+w # elementwise sum

array([ 5, -6,  5])

Elementwise product (?!)

In [38]:
v*w # elementwise product

array([  4, -16,   0])

## Arithmetic progressions

* `np.arange` is `start`, `stop`, `step`
* `np.linspace` is `first`,`last`,`number`

In [39]:
# Recall how you get a list of integer values
# in arithmetic progression using built-in stuff
list(range(3,20,2))

[3, 5, 7, 9, 11, 13, 15, 17, 19]

The similarly named `arange` from `numpy` does all this and more.

In [40]:
# From 2 up to but not including 3 in steps of size 0.1
np.arange(2,3,0.1)   # start, stop (not included), step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

When you know how many points you want, rather than the spacing, it's better to use `np.linspace`.  It takes the first and last elements, then the number of evenly-spaced points you want between them.

In [41]:
# From 12 to 14 in 6 steps; 
np.linspace( 12, 14, 6 )   # first, last, number of elements

array([12. , 12.4, 12.8, 13.2, 13.6, 14. ])

## Accessing items

Zero-based indexing.  For multi-dimensional arrays, give several integer indices separated by commas.

In [47]:
v = np.arange(8,24,3)
v

array([ 8, 11, 14, 17, 20, 23])

In [169]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[0,-2,16]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, -2, 16]])

In [170]:
A.shape

(4, 3)

### Vector indexing: Just like lists

In [48]:
v[0]

8

In [49]:
v[4]

20

In [51]:
v[-1]

23

### Multidimensional indexing: use a tuple of indices

For matrices, it's `[row, col]`

In [171]:
print(A)
print()
print(A[0,1])  # row 0 column 1

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 -2 16]]

2


Omitted indices at the end mean "everything from those dimensions"

In [54]:
A[2] # Row 2 of matrix A, considered as a vector

array([7, 8, 9])

In [172]:
A[:,1] # means all rows, column 1, as a vector --- i.e. column 1

array([ 2,  5,  8, -2])

Using `:` as an index means "everything from that dimension"

In [56]:
print(A)
print()
# All rows, column 1; that is, get column 1 as a vector
print(A[:,1])  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 -2 16]]

[ 2  5  8 -2]


In [173]:
L = [5,6,1,0,-2,6]
L[:]

[5, 6, 1, 0, -2, 6]

In [174]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, -2, 16]])

In [175]:
A[1:3, 0:2] # items in rows 1 and 2 that are also in cols 0 and 1 

array([[4, 5],
       [7, 8]])

In [176]:
A[::2, ::2] # even row and even col

array([[1, 3],
       [7, 9]])

In [ ]:
Image.fromarray(np.array(img)[100:200,180:380])  # one line crop

## Assigning items

**`numpy` arrays are mutable** 😱

Recall these are mutable:
* list
* dict
* set

Immutable:
* int
* float
* str
* bool
* tuple

In [186]:
np.array([1,2,3,4,5,6]).reshape( (2,3) )

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
A = np.arange(72).reshape( (8,9) ) + 5
A

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76]])

In [191]:
A[4,1] = -1 # item at row 4 col 1 set to -1

In [192]:
A

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, -1, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76]])

In [194]:
A[:4,5:] = 5 # items whose position is in row 0,1,2,3 and cols >=5
             # all set to five

In [195]:
A

array([[ 5,  6,  7,  8,  9,  5,  5,  5,  5],
       [14, 15, 16, 17, 18,  5,  5,  5,  5],
       [23, 24, 25, 26, 27,  5,  5,  5,  5],
       [32, 33, 34, 35, 36,  5,  5,  5,  5],
       [41, -1, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58],
       [59, 60, 61, 62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76]])

In [197]:
A[1] = 100  # everything in row 1 becomes 100

In [198]:
A

array([[  5,   6,   7,   8,   9,   5,   5,   5,   5],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 23,  24,  25,  26,  27,   5,   5,   5,   5],
       [ 32,  33,  34,  35,  36,   5,   5,   5,   5],
       [ 41,  -1,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,  62,  63,  64,  65,  66,  67],
       [ 68,  69,  70,  71,  72,  73,  74,  75,  76]])

In [199]:
np.array(A) # copy

array([[  5,   6,   7,   8,   9,   5,   5,   5,   5],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 23,  24,  25,  26,  27,   5,   5,   5,   5],
       [ 32,  33,  34,  35,  36,   5,   5,   5,   5],
       [ 41,  -1,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,  62,  63,  64,  65,  66,  67],
       [ 68,  69,  70,  71,  72,  73,  74,  75,  76]])

In [201]:
A.copy() # also a copy

array([[  5,   6,   7,   8,   9,   5,   5,   5,   5],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 23,  24,  25,  26,  27,   5,   5,   5,   5],
       [ 32,  33,  34,  35,  36,   5,   5,   5,   5],
       [ 41,  -1,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,  62,  63,  64,  65,  66,  67],
       [ 68,  69,  70,  71,  72,  73,  74,  75,  76]])

In [203]:
L = [ "a", "b", "c", "d", "e"]
M = L[1:-1] # slice of a list is a copy, indep from original

In [204]:
M

['b', 'c', 'd']

In [205]:
M[0] = "economic enthuasiasm"

In [206]:
M

['economic enthuasiasm', 'c', 'd']

In [207]:
L

['a', 'b', 'c', 'd', 'e']

In [208]:
A

array([[  5,   6,   7,   8,   9,   5,   5,   5,   5],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 23,  24,  25,  26,  27,   5,   5,   5,   5],
       [ 32,  33,  34,  35,  36,   5,   5,   5,   5],
       [ 41,  -1,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,  62,  63,  64,  65,  66,  67],
       [ 68,  69,  70,  71,  72,  73,  74,  75,  76]])

In [209]:
C = A[:,3:5] # all the rows, columns 3 and 4

In [210]:
C

array([[  8,   9],
       [100, 100],
       [ 26,  27],
       [ 35,  36],
       [ 44,  45],
       [ 53,  54],
       [ 62,  63],
       [ 71,  72]])

In [211]:
C[::2] = 0  # even numbered rows of C set to zero

In [212]:
C

array([[  0,   0],
       [100, 100],
       [  0,   0],
       [ 35,  36],
       [  0,   0],
       [ 53,  54],
       [  0,   0],
       [ 71,  72]])

In [213]:
A

array([[  5,   6,   7,   0,   0,   5,   5,   5,   5],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 23,  24,  25,   0,   0,   5,   5,   5,   5],
       [ 32,  33,  34,  35,  36,   5,   5,   5,   5],
       [ 41,  -1,  43,   0,   0,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,   0,   0,  64,  65,  66,  67],
       [ 68,  69,  70,  71,  72,  73,  74,  75,  76]])

## Slices

Can combine slice notation with multiple indices.

Slices return **views**, not copies.

## Equality and bool

`.all()` checks if an array of booleans is all `True`.

In [217]:
v = np.array([1,2,3])
w = np.array([1,2,5])

In [219]:
# common mistake
if v==w:
    print("They are equal")
else:
    print("They are not equal")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [220]:
# solution 1 (slow)
if np.all(v==w):
    print("They are equal")
else:
    print("They are not equal")

They are not equal


In [221]:
# solution 2 (fast)
if np.array_equal(v,w):
    print("They are equal")
else:
    print("They are not equal")

They are not equal


## Ufuncs

Functions that automatically apply to each entry in an array.

In [222]:
v = np.linspace(0,1,21)

In [224]:
v

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [226]:
# slow:    np array -> Python for loop -> list -> np array
np.array([ np.cos(x) for x in v ])

array([1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
       0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
       0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
       0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309,
       0.54030231])

In [227]:
# fast
np.cos(v)

array([1.        , 0.99875026, 0.99500417, 0.98877108, 0.98006658,
       0.96891242, 0.95533649, 0.93937271, 0.92106099, 0.9004471 ,
       0.87758256, 0.85252452, 0.82533561, 0.7960838 , 0.76484219,
       0.73168887, 0.69670671, 0.65998315, 0.62160997, 0.58168309,
       0.54030231])

In [228]:
v+1

array([1.  , 1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ,
       1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ])

In [229]:
v**2

array([0.    , 0.0025, 0.01  , 0.0225, 0.04  , 0.0625, 0.09  , 0.1225,
       0.16  , 0.2025, 0.25  , 0.3025, 0.36  , 0.4225, 0.49  , 0.5625,
       0.64  , 0.7225, 0.81  , 0.9025, 1.    ])

In [231]:
1 / (v+1)

array([1.        , 0.95238095, 0.90909091, 0.86956522, 0.83333333,
       0.8       , 0.76923077, 0.74074074, 0.71428571, 0.68965517,
       0.66666667, 0.64516129, 0.625     , 0.60606061, 0.58823529,
       0.57142857, 0.55555556, 0.54054054, 0.52631579, 0.51282051,
       0.5       ])

### Some arrays to operate on

### Examples of numpy ufuncs

In [232]:
def f(x):
    return 3*x**2 - 8*x + 14

In [233]:
f(2)

10

In [234]:
f(0.50)

10.75

In [236]:
np.array([ f(x) for x in v ])

array([14.    , 13.6075, 13.23  , 12.8675, 12.52  , 12.1875, 11.87  ,
       11.5675, 11.28  , 11.0075, 10.75  , 10.5075, 10.28  , 10.0675,
        9.87  ,  9.6875,  9.52  ,  9.3675,  9.23  ,  9.1075,  9.    ])

In [237]:
f(v)

array([14.    , 13.6075, 13.23  , 12.8675, 12.52  , 12.1875, 11.87  ,
       11.5675, 11.28  , 11.0075, 10.75  , 10.5075, 10.28  , 10.0675,
        9.87  ,  9.6875,  9.52  ,  9.3675,  9.23  ,  9.1075,  9.    ])

If you every type `for ... in NUMPY_ARRAY:`, there is probably a way to have numpy do the iteration for you, and that will be faster!

Let $f(x) = 3x^2 - 8x + 14$.  Apply $f$ to each element of array `v`.

## Broadcasting

## Aggregations

`sum`, `max`, `min`, `argmax`, `argmin`, `mean`, `all`, `any`, `array_equal`

## Masks

In [238]:
A

array([[  5,   6,   7,   0,   0,   5,   5,   5,   5],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 23,  24,  25,   0,   0,   5,   5,   5,   5],
       [ 32,  33,  34,  35,  36,   5,   5,   5,   5],
       [ 41,  -1,  43,   0,   0,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58],
       [ 59,  60,  61,   0,   0,  64,  65,  66,  67],
       [ 68,  69,  70,  71,  72,  73,  74,  75,  76]])

In [240]:
M = A > 55

In [241]:
M

array([[False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True,  True],
       [ True,  True,  True, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [243]:
A[M] # all the values in A at places where M is True, in a vector

array([100, 100, 100, 100, 100, 100, 100, 100, 100,  56,  57,  58,  59,
        60,  61,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76])

In [244]:
A[A>55] = 0   # replace everything greater than 55 with zero

In [245]:
A

array([[ 5,  6,  7,  0,  0,  5,  5,  5,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [23, 24, 25,  0,  0,  5,  5,  5,  5],
       [32, 33, 34, 35, 36,  5,  5,  5,  5],
       [41, -1, 43,  0,  0, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [246]:
A[A<0]=0  # clamp all values between 0 and 1
A[A>1]=1  # ...

In [247]:
A

array([[1, 1, 1, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Pillow integration

* `np.array(img)` just works, if `img` is a `PIL.Image` object
* Use `PIL.Image.fromarray(A)` to make an image from an array
    * Shape `(height,width)` and dtype `uint8` for grayscale
    * Shape `(height,width,3)` and dtype `uint8` for color (last axis is red, green, blue)